---
- hosts: all
  become: yes
  vars:
    init_setup_additional_packages:
      - vim
      - htop
    sshkey_url: "https://github.com/Chads.keys"
    cron_current_job_name: "current git ansible-pull repo location"
    cron_old_job_name: "old git ansible-pull repo location"
    cron_job: "date > ~/cron-test.txt" #"ansible-pull"
  roles:
    - ansible_az_init_setup