- hosts: localhost
  connection: local
  become: true
  vars:
    init_setup_additional_packages:
      - vim
      - htop
    users:
      - drok
      - ansible
    sshkey_url: "https://github.com/CJerkins.keys"
    cron_current_job_name: "current git ansible-pull repo location"
    cron_old_job_name: "old git ansible-pull repo location"
    cron_job: "date > ~/cron-test.txt" #"ansible-pull"
  tasks:
    - include: tasks/main.yml
