---
###Installing common packages###
- name: Install common CENTOS packages
  yum:
    name: "{{ init_setup_common_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install additional packages
  yum:
    name: "{{ item }}"
  with_items:
    - "{{ init_setup_additional_packages }}"
  when: ansible_facts['os_family'] == "RedHat"

  
- name: Install common UBUNTU packages
  apt:
    name: "{{ init_setup_common_packages }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Install additional packages
  apt:
    name: "{{ item }}"
  with_items:
    - "{{ init_setup_additional_packages }}"
  when: ansible_facts['os_family'] == "Debian"
